// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetOS.Data;

#nullable disable

namespace PetOS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503170458_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetOS.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("NVARCHAR2(600)");

                    b.Property<int>("PetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("RotinaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("RotinaId");

                    b.ToTable("TB_ALERTA", (string)null);
                });

            modelBuilder.Entity("PetOS.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DataNascimento")
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("Raca")
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)");

                    b.Property<string>("ResponsavelNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("ResponsavelTelefone")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("Id");

                    b.ToTable("PETS", (string)null);
                });

            modelBuilder.Entity("PetOS.Models.Rotina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Ativa")
                        .HasColumnType("NUMBER(5)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<string>("Frequencia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(48)");

                    b.Property<int>("PetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("ROTINAS", (string)null);
                });

            modelBuilder.Entity("PetOS.Models.Vacina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataAplicacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)");

                    b.Property<int>("PetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ProximaDose")
                        .HasColumnType("NVARCHAR2(10)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("VACINAS", (string)null);
                });

            modelBuilder.Entity("PetOS.Models.Alerta", b =>
                {
                    b.HasOne("PetOS.Models.Pet", "Pet")
                        .WithMany("Alertas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetOS.Models.Rotina", "Rotina")
                        .WithMany("Alertas")
                        .HasForeignKey("RotinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pet");

                    b.Navigation("Rotina");
                });

            modelBuilder.Entity("PetOS.Models.Rotina", b =>
                {
                    b.HasOne("PetOS.Models.Pet", "Pet")
                        .WithMany("Rotinas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetOS.Models.Vacina", b =>
                {
                    b.HasOne("PetOS.Models.Pet", "Pet")
                        .WithMany("Vacinas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetOS.Models.Pet", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Rotinas");

                    b.Navigation("Vacinas");
                });

            modelBuilder.Entity("PetOS.Models.Rotina", b =>
                {
                    b.Navigation("Alertas");
                });
#pragma warning restore 612, 618
        }
    }
}
